<div class="top-section-wrapper">
    <div class="bar-icon">
        <img src="<?php echo $block->getViewFileUrl('images/header/product-categories.png'); ?>" alt="product categories">
    </div>
    <div class="text">
        Kategorije proizvoda
    </div>
    <div class="label-line">
        <img src="<?php echo $block->getViewFileUrl('images/header/label_line.svg'); ?>" alt="label line">
    </div>
</div>
