<div class="footer-wrapper">
    <div class="links-footer-wrapper">
    <div class="links-wrapper">
        <h1 class="link-header">Sluzba za korisnike</h1>
        <ul class="links">
            <li><a href="#">Korisnicki racun</a></li>
            <li><a href="#">Status/Povijet narudzbi</a></li>
            <li><a href="#">Informacije o dostavi</a></li>
            <li><a href="#">Povrat proizvoda</a></li>
            <li><a href="#">Kontaktiranje nas</a></li>
        </ul>
    </div>
    <div class="links-wrapper">
        <h1 class="link-header">Vazne informacije</h1>
        <ul class="links">
            <li><a href="#">Kako kupovati</a></li>
            <li><a href="#">Kako do popusta</a></li>
            <li><a href="#">Privatnost i sigurnost podataka</a></li>
            <li><a href="#">Nacini placanja</a></li>
            <li><a href="#">Uvjeti kupnje</a></li>
        </ul>
    </div>
    <div class="links-wrapper-third">
        <h1 class="link-header">Saznajte vise</h1>
        <ul class="links">
            <li><a href="#">Kako kupovati</a></li>
            <li><a href="#">Kako do popusta</a></li>
            <li><a href="#">Privatnost i sigurnost podataka</a></li>
        </ul>
    </div>
    <div class="links-wrapper">
        <h1 class="link-header">Kontakt informacije</h1>
        <ul class="links">
            <li><a href="#">01 650 28 80</a></li>
            <li><a href="#">e-trgovina@nn.hr</a></li>
        </ul>
        <div class="social-icons">
            <div class="social-icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/facebook.png'); ?>" alt="facebook icon">
            </div>
            <div class="social-icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/twitter.png'); ?>" alt="twitter icon">
            </div>
            <div class="social-icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/linkedin.png'); ?>" alt="linkedin icon">
            </div>
        </div>
    </div>
    </div>

    <div class="footer-bottom-wrapper">
        <div class="footer-icons-wrapper">
            <div class="first-icon icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/mastercard.svg'); ?>" alt="mastercard icon">
            </div>
            <div class="second-icon icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/maestro.svg'); ?>" alt="maestro icon">
            </div>
            <div class="third-icon icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/diners_club.svg'); ?>" alt="diners club icon">
            </div>
            <div class="fourth-icon icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/visa.svg'); ?>" alt="visa icon">
            </div>
            <div class="fifth-icon icon">
                <img src="<?php echo $block->getViewFileUrl('images/footer/mastercard_secure_code.svg'); ?>" alt="mastercard secure  icon">
            </div>
        </div>
        <div class="copyright-bottom">
            &copy; Narodne novine d.d.2008-2019,Sva prava pridrzana
        </div>
    </div>
</div>
