<div class="banner-wrapper">
    <div class="banner">
        <div class="banner-icon">
            <img src="<?php echo $block->getViewFileUrl('images/login/posebne-pogodnosti@2x.png'); ?>" alt="first icon">
        </div>
        <div class="content">
            <h2 class="content-header">Posebne pogodnosti</h2>
            <p class="content-text">Pravnilnik „Kluba poslovnih korisnika" Narodnih novina d.d</p>
        </div>
    </div>

    <div class="banner">
        <div class="banner-icon">
            <img src="<?php echo $block->getViewFileUrl('images/login/dostava@2x.png'); ?>" alt="second icon">
        </div>
        <div class="content">
            <h2 class="content-header">Info o dostavi</h2>
            <p class="content-text">Uvijeti dostave i vazeci cjenici ugovornih partnera za dostavu</p>
        </div>
    </div>

    <div class="banner">
        <div class="banner-icon">
            <img src="<?php echo $block->getViewFileUrl('images/login/ugovorni-kupci@2x.png'); ?>" alt="third icon">
        </div>
        <div class="content">
            <h2 class="content-header">Ugovorni kupci</h2>
            <p class="content-text">Imate ugovor o poslovnoj suradnji sa Narodnim novinama d.d</p>
        </div>
    </div>

    <div class="banner">
        <div class="banner-icon">
            <img src="<?php echo $block->getViewFileUrl('images/login/outlet@2x.png'); ?>" alt="fourth icon">
        </div>
        <div class="content">
            <h2 class="content-header">Outlet</h2>
            <p class="content-text">Ponuda proizvoda iz proslih kolekcija po povoljnim cijenama</p>
        </div>
    </div>

</div>
